### ISSUE TITLE
undefined method `model_name' for ProveKeybase::Configuration:Class

### ISSUE THREAD

**Issue by MatteoJoliveau** [keybase/prove_keybase#4]
I'm following the starting guide and calling `https://localhost:3000/prove_keybase/config.json` yields this result since the Configuration class is not an ActiveModel object.

A workaround is to add the following lines to the `prove_keybase.rb` initializer:

```ruby
ProveKeybase::Configuration.class_eval do
  extend ActiveModel::Naming
  include ActiveModel::Conversion
  def persisted?
    false
  end
end
```

**Comment by xgess** [comment]
thanks. i'm on it. looks like something with a dependency update causes this behavior to change. fix coming...

**Comment by xgess** [comment]
hopefully fixed now 🤞 
lemme know either way when you get a chance.

**Comment by MatteoJoliveau** [comment]
@xgess it's working, thanks a lot!
